### ISSUE TITLE
[Question] Does robot support multiple nested machines?

### ISSUE THREAD

**Issue by kybarg** [matthewp/robot#99]
``` javascript
const first = createMachine({
  start: state(
    transition('DONE', 'done'),
  ),
  done: state(),
})

const second = createMachine({
  start: state(
    transition('DONE', 'done'),
  ),
  done: state(),
})

const machine = createMachine({
  start: state(
    transition('FIRST', 'first'),
    transition('SECOND', 'second'),
  ),
  first: invoke(first,
    transition('done', 'start'),
  ),
  second: invoke(second,
    transition('done', 'start'),
  ),
})
```

when calling `interpretedMachine.send('SECOND')` get an error
```console
uncaughtException TypeError: Cannot read property 'call' of undefined
    at Object.enter (\node_modules\robot3\dist\machine.js:90:13)
    at transitionTo (\node_modules\robot3\dist\machine.js:153:20)
    at send (\node_modules\robot3\dist\machine.js:164:12)
    at Object.send (\node_modules\robot3\dist\machine.js:171:20)
```

**Comment by matthewp** [comment]
It should support them. I see that you closed it, did you discover what the issue was?
